export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGOUT_USER_SUCCESS = 'LOGOUT_USER_SUCCESS';
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";

export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const LOAD_USER_SUCCESS = 'LOAD_USER_SUCCESS';

export const LOAD_PROJECT_SUCCESS = "LOAD_PROJECT_SUCCESS";
export const LOAD_PROJECTS_SUCCESS = 'LOAD_PROJECTS_SUCCESS';
export const CREATE_PROJECT_SUCCESS = 'CREATE_PROJECT_SUCCESS';
export const UPDATE_PROJECT_SUCCESS = 'UPDATE_PROJECT_SUCCESS';
